export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_MAIN_PAGE_REQUEST = "USER_MAIN_PAGE_REQUEST";
export const USER_MAIN_PAGE_SUCCESS = "USER_MAIN_PAGE_SUCCESS";
export const USER_MAIN_PAGE_FAIL = "USER_MAIN_PAGE_FAIL";

export const USER_ADD_WORKOUTS_REQUEST = "USER_ADD_WORKOUT_REQUEST";
export const USER_ADD_WORKOUTS_SUCCESS = "USER_ADD_WORKOUT_SUCCESS";
export const USER_ADD_WORKOUTS_FAIL = "USER_ADD_WORKOUT_FAIL";

export const USER_GET_WORKOUTS_REQUEST = "USER_GET_WORKOUT_REQUEST";
export const USER_GET_WORKOUTS_SUCCESS = "USER_GET_WORKOUT_SUCCESS";
export const USER_GET_WORKOUTS_FAIL = "USER_GET_WORKOUT_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_WORKOUT_OF_DAY_REQUEST = "USER_WORKOUT_OF_DAY_REQUEST";
export const USER_WORKOUT_OF_DAY_SUCCESS = "USER_WORKOUT_OF_DAY_SUCCESS";
export const USER_WORKOUT_OF_DAY_FAIL = "USER_WORKOUT_OF_DAY_FAIL";

export const USER_GET_WORKOUT_REQUEST = "USER_GET_WORKOUT_REQUEST";
export const USER_GET_WORKOUT_SUCCESS = "USER_GET_WORKOUT_SUCCESS";
export const USER_GET_WORKOUT_FAIL = "USER_GET_WORKOUT_FAIL";

export const USER_DELETE_WORKOUT_REQUEST = "USER_DELETE_WORKOUT_REQUEST";
export const USER_DELETE_WORKOUT_SUCCESS = "USER_DELETE_WORKOUT_SUCCESS";
export const USER_DELETE_WORKOUT_FAIL = "USER_DELETE_WORKOUT_FAIL";
